packages:
  - "packages/*"
minimumReleaseAge: 1440
blockExoticSubdeps: true
minimumReleaseAgeIgnoreMissingTime: true
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  fs-ext-extra-prebuilt: true
  unrs-resolver: true
