name: Bug report
description: Something isn't working
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happens
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: WP version, WC version, app version, browser/OS
