name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want and why?
    validations:
      required: true
