<?php
/**
 * WP Overnight invoice receipt template.
 *
 * Renders inline HTML by delegating to PDF Invoices & Packing Slips for WooCommerce.
 *
 * @package WCPOS\WooCommercePOS
 */

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals -- Template files use short variable names by convention.

if ( ! \defined( 'ABSPATH' ) ) {
	exit;
}

if ( empty( $order ) || ! \function_exists( 'wcpdf_get_document' ) ) {
	echo esc_html__( 'The WP Overnight invoice document is not available.', 'woocommerce-pos' );
	return;
}

$document = wcpdf_get_document( 'invoice', $order, true );

if ( ! $document || ! \is_callable( array( $document, 'get_html' ) ) ) {
	echo esc_html__( 'The WP Overnight invoice document could not be rendered for this order.', 'woocommerce-pos' );
	return;
}

echo $document->get_html(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Trusted HTML generated by the WP Overnight document API.
