<?php
/**
 * WP Overnight packing slip receipt template.
 *
 * Renders inline HTML by delegating to PDF Invoices & Packing Slips for WooCommerce.
 *
 * @package WCPOS\WooCommercePOS
 */

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals -- Template files use short variable names by convention.

if ( ! \defined( 'ABSPATH' ) ) {
	exit;
}

if ( empty( $order ) ) {
	echo esc_html__( 'The WP Overnight packing slip document is not available.', 'woocommerce-pos' );
	return;
}

$document = apply_filters( 'woocommerce_pos_wp_overnight_pdf_document', null, 'packing-slip', $order );

if ( null === $document && \function_exists( 'wcpdf_get_document' ) ) {
	$document = wcpdf_get_document( 'packing-slip', $order, true );
}

if ( ! $document || ! \is_callable( array( $document, 'get_html' ) ) ) {
	echo esc_html__( 'The WP Overnight packing slip document could not be rendered for this order.', 'woocommerce-pos' );
	return;
}

echo $document->get_html(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Trusted HTML generated by the WP Overnight document API.
