name: Manual Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        default: '0.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔖 Setup Release Version
        run: echo "VERSION=${{ github.event.inputs.releaseVersion }}" >> $GITHUB_ENV

      - name: 📦 Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: true
          prerelease: ${{ contains(env.VERSION, '-beta') }}

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
        with:
          version: '10.8.0'

      - name: 👷 Build
        run: |
          pnpm install --lockfile-only --ignore-scripts
          pnpm install --frozen-lockfile
          composer prefix-dependencies
          composer install --no-dev
          pnpm build

      - name: 📂 Sync to Temporary Directory
        run: |
          mkdir temp_dir
          rsync -av --prune-empty-dirs --exclude-from='.distignore' ./ temp_dir/
      
      - name: 📦 Compress and Upload ZIP
        run: |
          cd temp_dir
          zip -r ../woocommerce-pos.zip .
          cd ..
          gh release upload v${{ env.VERSION }} woocommerce-pos.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
