name: Sync assets with wordpress.org

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    name: Push assets to wporg
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        - name: WordPress.org plugin asset/readme update
          uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7 # stable
          env:
            SLUG: woocommerce-pos
            IGNORE_OTHER_FILES: true
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
