name: Deploy to WP Engine

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: '10.8.0'

      - name: 👷 Build
        run: |
          pnpm install
          composer prefix-dependencies
          composer install --no-dev
          pnpm settings build
          pnpm analytics build
          pnpm template-gallery build

      - name: 🚀 Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@7bdbfb62eb657ae92afb91cb889d9c3fb36ef6c0 # v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: wcposdev
          REMOTE_PATH: "wp-content/plugins/woocommerce-pos"
          FLAGS: >-
            -azvr --inplace --delete --delete-excluded --exclude-from=.distignore
            -e "ssh -o StrictHostKeyChecking=no -o ControlMaster=no -p 22 -i /github/home/.ssh/wpe_id_rsa"
          CACHE_CLEAR: TRUE
