name: Deploy to WP Engine

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
        with:
          version: '10.8.0'

      - name: 👷 Build
        run: |
          pnpm install
          composer prefix-dependencies
          composer install --no-dev
          pnpm build

      - name: 🚀 Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@7bdbfb62eb657ae92afb91cb889d9c3fb36ef6c0 # v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: wcposdev
          REMOTE_PATH: "wp-content/plugins/woocommerce-pos"
          FLAGS: >-
            -azvr --inplace --delete --delete-excluded --exclude-from=.distignore
            -e "ssh -o StrictHostKeyChecking=no -o ControlMaster=no -p 22 -i /github/home/.ssh/wpe_id_rsa"
          CACHE_CLEAR: TRUE
