name: Deploy to WordPress.org

on:
  release:
    types: [ released ]
  workflow_dispatch:

jobs:
  tag:
    name: New release

    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: '10.8.0'

      - name: 👷 Build
        run: |
          pnpm install
          composer prefix-dependencies
          composer install --no-dev
          pnpm build

      - name: 📦 WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2 # stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: woocommerce-pos
        continue-on-error: true
